// <auto-generated />
using System;
using ClientRegister.Data.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClientRegister.Data.Migrations
{
    [DbContext(typeof(ClientDbContext))]
    partial class ClientDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ClientRegister.Support.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Disease")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("DriverLicense")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDiabetic")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OtherDisease")
                        .HasColumnType("bit");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UseGlasses")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 21,
                            DNI = 12345672,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverLicense = false,
                            FullName = "Client Name1",
                            Gender = "Female",
                            IsActive = true,
                            IsDiabetic = false,
                            ModifiedAt = new DateTime(2022, 5, 6, 21, 43, 49, 809, DateTimeKind.Local).AddTicks(5733),
                            OtherDisease = false,
                            UseGlasses = true
                        },
                        new
                        {
                            Id = 2,
                            Age = 22,
                            DNI = 12345673,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverLicense = false,
                            FullName = "Client Name2",
                            Gender = "Male",
                            IsActive = true,
                            IsDiabetic = false,
                            ModifiedAt = new DateTime(2022, 5, 6, 21, 43, 49, 812, DateTimeKind.Local).AddTicks(2278),
                            OtherDisease = false,
                            UseGlasses = true
                        },
                        new
                        {
                            Id = 3,
                            Age = 23,
                            DNI = 12345674,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverLicense = false,
                            FullName = "Client Name3",
                            Gender = "Female",
                            IsActive = true,
                            IsDiabetic = false,
                            ModifiedAt = new DateTime(2022, 5, 6, 21, 43, 49, 812, DateTimeKind.Local).AddTicks(2423),
                            OtherDisease = false,
                            UseGlasses = true
                        },
                        new
                        {
                            Id = 4,
                            Age = 24,
                            DNI = 12345675,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverLicense = false,
                            FullName = "Client Name4",
                            Gender = "Male",
                            IsActive = true,
                            IsDiabetic = false,
                            ModifiedAt = new DateTime(2022, 5, 6, 21, 43, 49, 812, DateTimeKind.Local).AddTicks(2432),
                            OtherDisease = false,
                            UseGlasses = true
                        },
                        new
                        {
                            Id = 5,
                            Age = 25,
                            DNI = 12345676,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverLicense = false,
                            FullName = "Client Name5",
                            Gender = "Female",
                            IsActive = true,
                            IsDiabetic = false,
                            ModifiedAt = new DateTime(2022, 5, 6, 21, 43, 49, 812, DateTimeKind.Local).AddTicks(2438),
                            OtherDisease = false,
                            UseGlasses = true
                        },
                        new
                        {
                            Id = 6,
                            Age = 26,
                            DNI = 12345677,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverLicense = false,
                            FullName = "Client Name6",
                            Gender = "Male",
                            IsActive = true,
                            IsDiabetic = false,
                            ModifiedAt = new DateTime(2022, 5, 6, 21, 43, 49, 812, DateTimeKind.Local).AddTicks(2448),
                            OtherDisease = false,
                            UseGlasses = true
                        },
                        new
                        {
                            Id = 7,
                            Age = 27,
                            DNI = 12345678,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverLicense = false,
                            FullName = "Client Name7",
                            Gender = "Female",
                            IsActive = true,
                            IsDiabetic = false,
                            ModifiedAt = new DateTime(2022, 5, 6, 21, 43, 49, 812, DateTimeKind.Local).AddTicks(2453),
                            OtherDisease = false,
                            UseGlasses = true
                        },
                        new
                        {
                            Id = 8,
                            Age = 28,
                            DNI = 12345679,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverLicense = false,
                            FullName = "Client Name8",
                            Gender = "Male",
                            IsActive = true,
                            IsDiabetic = false,
                            ModifiedAt = new DateTime(2022, 5, 6, 21, 43, 49, 812, DateTimeKind.Local).AddTicks(2459),
                            OtherDisease = false,
                            UseGlasses = true
                        });
                });

            modelBuilder.Entity("ClientRegister.Support.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Administrator rol type",
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 5, 6, 21, 43, 49, 818, DateTimeKind.Local).AddTicks(1712),
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("ClientRegister.Support.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("nvarchar(65)");

                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RolesId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 5, 6, 21, 43, 49, 817, DateTimeKind.Local).AddTicks(5635),
                            Password = "e7cf3ef4f17c3999a94f2c6f612e8a888e5b1026878e4e19398b23bd38ec221a",
                            RolesId = 1,
                            UserName = "Admin 1"
                        },
                        new
                        {
                            Id = 2,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 5, 6, 21, 43, 49, 817, DateTimeKind.Local).AddTicks(6312),
                            Password = "e7cf3ef4f17c3999a94f2c6f612e8a888e5b1026878e4e19398b23bd38ec221a",
                            RolesId = 1,
                            UserName = "Admin 2"
                        },
                        new
                        {
                            Id = 3,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 5, 6, 21, 43, 49, 817, DateTimeKind.Local).AddTicks(6396),
                            Password = "e7cf3ef4f17c3999a94f2c6f612e8a888e5b1026878e4e19398b23bd38ec221a",
                            RolesId = 1,
                            UserName = "Admin 3"
                        },
                        new
                        {
                            Id = 4,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 5, 6, 21, 43, 49, 817, DateTimeKind.Local).AddTicks(6490),
                            Password = "e7cf3ef4f17c3999a94f2c6f612e8a888e5b1026878e4e19398b23bd38ec221a",
                            RolesId = 1,
                            UserName = "Admin 4"
                        },
                        new
                        {
                            Id = 5,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2022, 5, 6, 21, 43, 49, 817, DateTimeKind.Local).AddTicks(6610),
                            Password = "e7cf3ef4f17c3999a94f2c6f612e8a888e5b1026878e4e19398b23bd38ec221a",
                            RolesId = 1,
                            UserName = "Admin 5"
                        });
                });

            modelBuilder.Entity("ClientRegister.Support.Entities.User", b =>
                {
                    b.HasOne("ClientRegister.Support.Entities.Rol", "Roles")
                        .WithMany("Users")
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("ClientRegister.Support.Entities.Rol", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
